### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [EndurableFawn/ConsoleDu#1]
- [x] Лучше отделить разбор аргументов командной строки и, собственно, обработку.
- [x] Использовать статические поля класса в расчёте на то, что Вам понадобится только один экземпляр класса не самая лучшая идея. Переделайте так, чтобы основная часть была в классе, который принимает параметры (уже разобранные) как аргументы и не использует статические поля без необходимости.

**Comment by EndurableFawn** [comment]
Исправлено

**Comment by maximpetrov** [comment]
Создав отдельный класс, Вы не перенесли разбор аргументов полностью в него. Вы всё равно передаёте в метод `du` весь массив аргументов и внутри частично занимаетесь его разбором (проверяете на неравенство возможным параметрам). Кроме того, возможно я не совсем понятно выразился, но я хочу чтобы как минимум метод `du` был нестатическим, а параметры сохранялись в конструкторе в поля класса.

**Comment by EndurableFawn** [comment]
Исправлено

**Comment by maximpetrov** [comment]
Метод `human` можно сделать нестатическим, тогда Вам не придётся передавать в него `base`. А вот список размерностей можно вынести как статическую константу, причем её можно и обычным массивом сделать.

**Comment by EndurableFawn** [comment]
Исправлено

**Comment by maximpetrov** [comment]
Вот здесь ещё замените `"B"` на нулевой элемент массива.
https://github.com/EndurableFawn/ConsoleDu/blob/54d06a6e5fae1651778596029b887c0e19180185/src/main/ConsoleDu.java#L94

**Comment by EndurableFawn** [comment]
Исправлено
